// doc-generator produces docs/metrics.md from the metric and alert
// definitions in the Go source. Run via `make generate`.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"

	"github.com/csi-addons/csi-volume-device-exporter/pkg/monitoring/rules/alerts"
)

type metricDef struct {
	Name   string
	Type   string
	Help   string
	Labels []string
}

var metricDefs = []metricDef{
	{
		Name:   "csiaddons_volume_node_device_info",
		Type:   "Gauge",
		Help:   "Maps CSI volumes to node block devices. Value is always 1.",
		Labels: []string{"node", "volume_handle", "driver", "device"},
	},
	{
		Name:   "csiaddons_volume_device_exporter_discovery_errors_total",
		Type:   "Counter",
		Help:   "Total number of discovery errors by discoverer.",
		Labels: []string{"discoverer"},
	},
	{
		Name:   "csiaddons_volume_device_exporter_volumes_discovered",
		Type:   "Gauge",
		Help:   "Number of volumes discovered per driver.",
		Labels: []string{"driver"},
	},
	{
		Name:   "csiaddons_volume_device_exporter_last_successful_discovery_timestamp_seconds",
		Type:   "Gauge",
		Help:   "Unix timestamp of last successful discovery cycle.",
		Labels: nil,
	},
}

type alertDef struct {
	Name     string
	Severity string
	For      string
	Summary  string
}

const docTemplate = `# Metrics and Alerts Reference

This document is auto-generated by ` + "`make generate`" + `. Do not edit manually.

## Metrics

| Name | Type | Labels | Description |
|------|------|--------|-------------|
{{- range .Metrics }}
| ` + "`{{ .Name }}`" + ` | {{ .Type }} | {{ joinLabels .Labels }} | {{ .Help }} |
{{- end }}

## Alerts

| Name | Severity | For | Summary |
|------|----------|-----|---------|
{{- range .Alerts }}
| ` + "`{{ .Name }}`" + ` | {{ .Severity }} | {{ .For }} | {{ .Summary }} |
{{- end }}
`

type templateData struct {
	Metrics []metricDef
	Alerts  []alertDef
}

func main() {
	_, thisFile, _, _ := runtime.Caller(0)
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")
	outPath := filepath.Join(repoRoot, "docs", "metrics.md")

	var alertDefs []alertDef
	for _, a := range alerts.All() {
		severity := a.Labels["severity"]
		summary := a.Annotations["summary"]
		alertDefs = append(alertDefs, alertDef{
			Name:     a.Name,
			Severity: severity,
			For:      a.For,
			Summary:  summary,
		})
	}

	data := templateData{
		Metrics: metricDefs,
		Alerts:  alertDefs,
	}

	funcMap := template.FuncMap{
		"joinLabels": func(labels []string) string {
			if len(labels) == 0 {
				return "—"
			}
			quoted := make([]string, len(labels))
			for i, l := range labels {
				quoted[i] = "`" + l + "`"
			}
			return strings.Join(quoted, ", ")
		},
	}

	tmpl, err := template.New("doc").Funcs(funcMap).Parse(docTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "doc-generator: template parse error: %v\n", err)
		os.Exit(1)
	}

	f, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "doc-generator: %v\n", err)
		os.Exit(1)
	}

	if err := tmpl.Execute(f, data); err != nil {
		_ = f.Close()
		fmt.Fprintf(os.Stderr, "doc-generator: template execute error: %v\n", err)
		os.Exit(1)
	}

	if err := f.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "doc-generator: close: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote docs/metrics.md")
}
