---
name: Run Golang tests

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run "make test"
        run: make test

      - name: Run "make vet"
        run: make vet

      - name: Check for uncommitted changes
        run: make check-all-committed

      - name: Show the uncommitted "git diff"
        if: ${{ failure() }}
        run: git diff ; false

  test-alerts:
    name: test-alerts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run "make test-alerts"
        run: make test-alerts
        env:
          CRI: docker

  go_mod_verify:
    name: go_mod_verify
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Verify Go modules
        run: go mod verify
